version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cardradar_postgres
    restart: always
    environment:
      POSTGRES_USER: cardradar
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cardradar_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
