// Compiles the Claude Design pages in design/*.dc.html into files the static site loads:
//   public/<name>.tpl.js   the page markup as a function: (vm, T, A, H) => html string
//   public/<name>.css      the design's <style> plus its :hover rules
// The template language is small: <sc-if value>, <sc-for list as>, {{ path }}, style-hover, ref.
// Run after pulling a new export from claude.ai/design: node scripts/dc-compile.js
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PAGES = ['landing', 'dashboard'];

// The design's DOM events, as the browser names them. onChange is 'input' on text inputs and 'change' on <select>.
const EVENTS = {
  onClick: 'click', onKeyDown: 'keydown', onFocus: 'focusin', onBlur: 'focusout', onMouseDown: 'mousedown',
  onMouseEnter: 'mouseenter', onMouseLeave: 'mouseleave', onMouseMove: 'mousemove', onPointerMove: 'pointermove',
  onPointerLeave: 'pointerleave', onSubmit: 'submit',
};

const PATH = /^\s*\{\{\s*([A-Za-z_$][\w$]*(?:\.[\w$]+)*)\s*\}\}\s*$/;
const KEYWORDS = new Set(['true', 'false', 'null', 'undefined']);

const jsText = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

function compile(name) {
  const src = fs.readFileSync(path.join(ROOT, 'design', `${name}.dc.html`), 'utf8');
  const style = (/<helmet>[\s\S]*?<style>([\s\S]*?)<\/style>/.exec(src) || [])[1] || '';
  // The dashboard project keeps its files under public/; on the site they sit at the root.
  const body = src.slice(src.indexOf('<x-dc>') + 6, src.lastIndexOf('</x-dc>')).replace(/<helmet>[\s\S]*?<\/helmet>/, '').replace(/(src|href)="public\//g, '$1="');

  const roots = new Set();
  const scope = [];
  const hovers = new Map();
  const use = (expr) => {
    const root = expr.split('.')[0];
    if (!scope.includes(root) && !KEYWORDS.has(root)) roots.add(root);
    return expr;
  };
  // Static text with {{ path }} holes becomes a template literal; attribute quotes are escaped at run time by T.
  const text = (s) => s.split(/(\{\{\s*[^}]*?\s*\}\})/).map((part) => {
    const m = PATH.exec(part);
    return m ? `\${T(${use(m[1])})}` : jsText(part);
  }).join('');

  const tag = (raw) => {
    const [, close, tagName, rest, selfClose] = /^<(\/?)([\w-]+)([\s\S]*?)(\/?)>$/.exec(raw);
    if (close) return null;
    const attrs = [];
    const re = /([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'))?/g;
    for (let m; (m = re.exec(rest));) attrs.push([m[1], m[2] ?? m[3]]);

    let hover = null;
    const out = [];
    let classNames = '';
    for (const [key, value] of attrs) {
      if (key.startsWith('hint-')) continue;
      if (key === 'style-hover') { hover = value; continue; }
      if (key === 'class') { classNames = value; continue; }
      const hole = value === undefined ? null : PATH.exec(value);
      if (key === 'ref' && hole) { out.push(` data-ref="${hole[1]}"`); continue; }
      if (EVENTS[key] || key === 'onChange') {
        if (!hole) throw new Error(`${name}: ${key} needs a {{ handler }}`);
        const type = key === 'onChange' ? (tagName === 'select' ? 'change' : 'input') : EVENTS[key];
        out.push(`\${A('data-h-${type}', H(${use(hole[1])}))}`);
        continue;
      }
      if (hole) out.push(`\${A('${key}', ${use(hole[1])})}`);
      else if (value === undefined) out.push(` ${key}`);
      else out.push(` ${key}="${text(value)}"`);
    }
    if (hover) {
      if (!hovers.has(hover)) hovers.set(hover, `hv${hovers.size + 1}`);
      classNames = `${classNames} ${hovers.get(hover)}`.trim();
    }
    if (classNames) out.unshift(` class="${classNames}"`);
    return `<${tagName}${out.join('')}${selfClose ? ' /' : ''}>`;
  };

  let js = '';
  for (const raw of body.match(/<!--[\s\S]*?-->|<\/?[a-zA-Z][^>]*>|[^<]+|</g) || []) {
    if (raw.startsWith('<!--')) continue;
    if (raw.startsWith('</sc-if')) js += '` : \'\'}';
    else if (raw.startsWith('</sc-for')) { js += '`).join(\'\')}'; scope.pop(); }
    else if (raw.startsWith('<sc-if')) js += `\${${use(PATH.exec(/\svalue="([^"]*)"/.exec(raw)[1])[1])} ? \``;
    else if (raw.startsWith('<sc-for')) {
      const list = PATH.exec(/list="([^"]*)"/.exec(raw)[1])[1];
      const as = /\bas="([^"]*)"/.exec(raw)[1];
      js += `\${(${use(list)} || []).map((${as}) => \``;
      scope.push(as);
    } else if (raw.startsWith('</')) js += raw;
    else if (raw.startsWith('<') && raw.length > 1) js += tag(raw);
    else js += text(raw);
  }

  const hoverCss = [...hovers].map(([decls, cls]) => {
    const important = decls.split(';').map((d) => d.trim()).filter(Boolean).map((d) => `${d}!important`).join(';');
    return `.${cls}:hover{${important}}`;
  }).join('\n');

  const header = `// GENERATED by scripts/dc-compile.js from design/${name}.dc.html. Do not edit; edit the design and recompile.\n`;
  const tpl = `${header}(window.CRT = window.CRT || {}).${name} = function (v, T, A, H) {\n  const { ${[...roots].sort().join(', ')} } = v;\n  return \`${js}\`;\n};\n`;
  fs.writeFileSync(path.join(ROOT, 'public', `${name}.tpl.js`), tpl);
  fs.writeFileSync(path.join(ROOT, 'public', `${name}.css`), `/* GENERATED by scripts/dc-compile.js from design/${name}.dc.html */\n${style.trim()}\n${hoverCss}\n`);
  console.log(`${name}: ${roots.size} bindings, ${hovers.size} hover rules`);
}

PAGES.forEach(compile);
